yelp_api_host: "api.yelp.com"
YWSID: "1GDLbc7Csr05jHJQao-dA"
yelp_consumer_key: "fDWrOEMzIJJWuJP7v2LPEA"
yelp_consumer_secret: "rMP0D7yqudv7qWRTSILkKeluPM4"
yelp_token_secret: "gE8v1LjRc5ByoMP7iPF9PgSxnkE"
yelp_token: "YZ7gs5VRlG1a191tvcpEGrE5C7mRUhtA"